# Generated by Django 6.0.6 on 2026-07-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommapp", "0002_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.IntegerField(max_length=10)),
                ("address", models.TextField(max_length=300)),
                ("city", models.TextField(max_length=50)),
                ("state", models.TextField(max_length=50)),
                ("pincode", models.IntegerField()),
            ],
        ),
    ]
