# Generated by Django 6.0.6 on 2026-07-17 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommapp", "0009_shippingaddress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="created_at",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="payment_method",
            field=models.CharField(default="COD", max_length=20),
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="ecommapp.order"
            ),
        ),
    ]
